### ISSUE TITLE
pull  wahyd4/aria2-ui: nextcloud 报500错误

### ISSUE THREAD

**Issue by ghost** [wahyd4/aria2-ariang-x-docker-compose#76]
root@localhost Aria2]# ./start.sh 
access control disabled, clients can connect from any host
Pulling nextcloud (nextcloud:latest)...
latest: Pulling from library/nextcloud
b8f262c62ec6: Already exists
b8f262c62ec6: Already exists
a98660e7def6: Pull complete
4d75689ceb37: Pull complete
639eb0368afa: Pull complete
99e337926e9c: Pull complete
431d44b3ce98: Pull complete
beb665ea0e0e: Pull complete
1914f5ed0362: Pull complete
3bb658c14677: Pull complete
6a4699b1063e: Pull complete
d23f6accef3d: Pull complete
3814846efc9c: Pull complete
e14c865e4394: Pull complete
2133ee9f21fd: Pull complete
f82b4703e01c: Pull complete
2b2b4d327bbf: Pull complete
fae4375a7bd4: Pull complete
23c715b12930: Pull complete
c24f6ede7288: Pull complete
401e9a63dae3: Pull complete
74f75341c74f: Pull complete
Digest: sha256:b2fb8ff34180ab1c61372809dd137a57c11b1c03190f33886e5f22c3bcb920f1
Status: Downloaded newer image for nextcloud:latest
Pulling aria2 (wahyd4/aria2-ui:nextcloud)...
nextcloud: Pulling from wahyd4/aria2-ui
ae4a0e1e8235: Already exists
4dae8b7b13d4: Pulling fs layer
1bdba81e989e: Pulling fs layer
7f9a05b3a37a: Pulling fs layer
6478cecf5e50: Waiting
17cd2e2a4878: Waiting
c03fdb1d0702: Waiting
ERROR: error pulling image configuration: received unexpected HTTP status: 500 Internal Server Error

**Comment by wahyd4** [comment]
Hi @anhualin921011 , di you see `error pulling image configuration` in the last sentence?  Which means there was something went wrong when you pulled the image. This issue is not related to this project, instead of might because of the network or some other issues related to Docker.

You can retry the command or set up a Docker proxy, e.g. [Alicloud](https://yq.aliyun.com/articles/29941)

Last but not least, if you find this project is useful, please consider to donate through Wechat to support this opensource project, thanks.
